on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: oss-gate/issue-cleaner@v2
        with:
          DOORKEEPER_GROUP: oss-gate
        env:
          DOORKEEPER_TOKEN: ${{ secrets.DOORKEEPER_TOKEN }}
